FROM ubuntu:22.04
RUN apt-get update && apt-get install -y python3.10 python3.10-pip
COPY requirements.txt .
RUN pip3 install --no-cache-dir -r requirements.txt
COPY . .
RUN apt-get autoremove -y && apt-get clean && rm -rf /var/lib/apt/lists/*
CMD ["python3.10", "/app/main.py"]